version: '3.4'

services:
  talkserver:
    image: ${DOCKER_REGISTRY-}talkserver
    build:
      context: .
      dockerfile: TalkServer/Dockerfile

    talkRedis:
        image: redis
        command: redis-server --appendonly yes
        ports: 
            - 6379:6379

    talkSQL: 
        image: d58526/talkSQL
        ports:
            - 1433:1433